--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/singleton-trait
branches:
  - main
projects:
  singleton-trait:
    model: virion
    type: library
    lint:
      phpstan: false
...
